RESULTS_DIRECTORY = "Results"

MASTER_SEED_RANGE = (100000, 999999)

DEFAULT_NUM_LOGICAL_QUBITS = 24
DEFAULT_NUM_QPUS = 6
DEFAULT_QPU_CAPACITY = 4
DEFAULT_BENCHMARK = "layered_random"
DEFAULT_BENCHMARK_LAYERS = 16
DEFAULT_TOPOLOGY = "random_connected"
DEFAULT_SIMULATION_STEPS = 50
DEFAULT_CONGESTION_THRESHOLD = 0.60

TOPOLOGY_EXTRA_LINK_PROBABILITY = 0.25

LINK_LATENCY_RANGE = (5, 30)
LINK_FIDELITY_RANGE = (0.90, 0.995)
LINK_CAPACITY_RANGE = (4, 12)
LINK_BELL_PAIR_POOL_RANGE = (24, 64)
LINK_BELL_PAIR_REGENERATION_RANGE = (8.0, 20.0)

EVOLUTION_LATENCY_STEP_FRACTION = 0.08
EVOLUTION_LATENCY_BOUNDS_FRACTION = (0.5, 2.0)
EVOLUTION_FIDELITY_STEP = 0.004
EVOLUTION_FIDELITY_MAX_DEGRADATION = 0.08
EVOLUTION_FIDELITY_MAX_IMPROVEMENT = 0.005
EVOLUTION_CAPACITY_CHANGE_PROBABILITY = 0.10
EVOLUTION_CAPACITY_MAX_DEVIATION = 2
EVOLUTION_MEAN_REVERSION = 0.15
EVOLUTION_REGENERATION_JITTER = 0.25

LOAD_PER_REMOTE_INTERACTION = 1.0
BELL_PAIRS_PER_UNIT_LOAD = 1.0
WINDOW_DURATION = 30.0
MAX_QUEUE_AGE_WINDOWS = 8

CANDIDATE_ROUTES_PER_PAIR = 4
MAX_EXTRA_HOPS = 2

ROUTE_COST_LATENCY_WEIGHT = 1.0
ROUTE_COST_HOP_WEIGHT = 5.0
ROUTE_COST_INFIDELITY_WEIGHT = 100.0
ROUTE_COST_UTILIZATION_WEIGHT = 20.0
ROUTE_COST_CONGESTION_WEIGHT = 60.0
ROUTE_COST_BELL_SCARCITY_WEIGHT = 20.0

QUBO_ONEHOT_PENALTY_SCALE = 3.0
QUBO_CAPACITY_PENALTY_SCALE = 4.0
QUBO_CONTENTION_WEIGHT = 1.5
CLASSICAL_EXHAUSTIVE_LIMIT = 20000

USE_QUANTUM_OPTIMIZER = True
QAOA_REPS = 2
QAOA_MAX_QUBITS = 12
QAOA_MAXITER = 60
QAOA_SHOTS = 1024
QAOA_SELECTION_POLICY = "qaoa_first"

REPARTITION_TRIGGER_REASONS = ("congestion", "resource")
CONGESTION_PERSISTENCE_WINDOWS = 2
RESOURCE_DEFERRAL_PERSISTENCE_WINDOWS = 2
TRIGGER_LATENCY_LIMIT = 45.0
TRIGGER_FIDELITY_LIMIT = 0.85
REPARTITION_COOLDOWN_WINDOWS = 3
REPARTITION_LOOKAHEAD_WINDOWS = None
REPARTITION_MAX_MOVES_PER_EVENT = 2
REPARTITION_IMPROVEMENT_MARGIN = 0.05
REPARTITION_DEFERRAL_PENALTY = 200.0
REPARTITION_MIGRATION_WEIGHT = 1.0

PARTITION_KL_RESTARTS = 8
PARTITION_REFINEMENT_PASSES = 3
